name: certora-gsm-4626

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Certora/certora-run-action@v2
        with:
          cli-version: 7.31.2
          configurations: |-
            certora/gsm/conf/gsm4626/optimality4626.conf --rule R1_optimalityOfBuyAsset_v1
            certora/gsm/conf/gsm4626/optimality4626.conf --rule R3_optimalityOfSellAsset_v1
          solc-versions: 0.8.20
          comment-fail-only: false
          solc-remove-version-prefix: "0."
          job-name: "Certora Prover Run"
          certora-key: ${{ secrets.CERTORAKEY }}
          install-java: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
